config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  get 'email_messages/index'
  post 'email_messages/create'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  # GET /test_passages/1/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :text, presence: true

  validate :validate_max

  private

  def validate_max
    question_count = question.nil? ? 0 : question.answers.size
    if question_count >= 4
      errors.add(:Quantity, 'Question must have 4 answers max!')
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :tests

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/email_message.rb
# frozen_string_literal: true

class EmailMessage
  include ActiveModel::Model
  attr_accessor :email, :name, :text

  validates :email, presence: true, format: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
  validates :text, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :text, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :author, class_name: 'User', foreign_key: 'author_id', optional: true

  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  scope :simple, -> { where(level: [0..1]) }
  scope :middle, -> { where(level: [2..4]) }
  scope :hard, -> { where(level: [5..]) } # or [5..Float::INFINITY]

  scope :with_questions, -> { joins(:questions).group('tests.id') }

  scope :by_category_title_repo, ->(category_title) {
                                  joins(:category)
                                  .where(categories: { title: category_title })
                                  .order(id: :desc)
                                  .pluck(:title)
                                }

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than: 0 }
  # unique 'title + level' pair values
  validates :title, uniqueness: {
    scope: :level, message: 'We already have this test in Db' }

  #def self.by_category_title_repo(category_title)
  #    Test
  #      .joins(:category)
  #      .where(categories: { title: category_title })
  #      .order('tests.id DESC')
  #      .pluck(:title)
  #  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  TEST_PASSED_PERCENT_VALUE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def passed?
    result_percent >= TEST_PASSED_PERCENT_VALUE
  end

  def expired?
    # TestPassage created + Test.timer value < current time
    (created_at + self.test.timer * 60) < Time.zone.now
  end

  def timer_seconds_left
    # returns absolute value in seconds
    (Time.zone.now - (created_at + self.test.timer * 60)).to_i.abs
  end

  def result_percent
    percent = self.correct_questions.to_f / self.test.questions.count.to_f * 100
    percent.to_i
  end

  def passage_percent
    # current question index + 1 removed due progress bar incorrect visualization
    self.test.questions.index(current_question) * 100 / self.test.questions.count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/tests_user.rb
# frozen_string_literal: true

class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id'
  has_many :gists

  scope :history, ->(user, level) { user.tests.where(level: level) }

  validates :email, uniqueness: true, format: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
  validates :first_name, presence: true
  validates :last_name, presence: true

  def admin?
    is_a?(Admin) ? true : false
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/users_history.rb
class UsersHistory < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :user_name_params, if: :devise_controller?

  def default_url_options
    I18n.locale == I18n.default_locale ? {} : { lang: I18n.locale }
  end

  private

  def set_locale
    I18n.locale = I18n.locale_available?(params[:lang]) ? params[:lang] : I18n.default_locale
  end

  def after_sign_in_path_for(user)
    flash[:notice] = "#{t('.hello')}, #{user.first_name} #{user.last_name}!"

    user.admin? ? admin_tests_path : tests_path
  end

  def user_name_params
    devise_parameter_sanitizer.permit(:login, keys: %i[first_name last_name])
  end
end

app/controllers/tests_controller.rb
# frozen_string_literal: true

class TestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tests = Test.with_questions
  end

  def start
    @test = Test.find(params[:id])
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_year
    DateTime.now.year
  end

  def github_url(author, repo)
    link_to 'Github', "https://github.com/#{author}/#{repo}"
  end

  def flash_message(type)
    content_tag :p, flash[type], class: "flash #{type}" if flash[type]
  end

  def alert_class(type)
    case type
    when 'notice' then 'info'
    when 'success' then 'success'
    when 'error' then 'danger'
    when 'alert' then 'warning'
    else 'bug'
    end
  end
end

app/helpers/email_messages_helper.rb
# frozen_string_literal: true

module EmailMessagesHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    "#{question.new_record? ? 'Create new' : 'Edit'} "\
      "'#{question.test.title}' test Question"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
# frozen_string_literal: true

module TestsHelper
  def questions_count(test)
    test.questions.count
  end
end

app/views/admin/_nav.html.erb
<nav class='navbar navbar-light bg-light'>
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

  <span class="navbar-text small">
    <% if user_signed_in? %>
      <%= t('.welcome', email_address: current_user.email) %> |
      <%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to t('.sign_up'), new_user_registration_path %> |
        <%= link_to t('.log_in'), user_session_path %>
    <% end %> |
    <%= link_to t('.contacts'), email_messages_index_path %>
  </span>
</nav>

app/views/layouts/_footer.html.erb
<hr/>
<div class="small mr-3">
  <h5>nafanasev, <%= current_year %></h5>
  <%= github_url(:middledeveloper, :TestGuru) %>
  <p>Приложение TestGuru, на базе Ruby on Rails.</p>
  <%= link_to 'Учебный проект в онлайн-школе Thinknetica',
              'http://thinknetica.com' %>
</div>

app/views/layouts/_nav.html.erb
<nav class='navbar navbar-light bg-light'>
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

  <span class="navbar-text small">
    <% if user_signed_in? %>
      <%= t('.welcome', name: current_user.first_name + ' ' + current_user.last_name) %> |
      <% if current_user.admin? %>
        <%= link_to t('.admin_panel'), admin_tests_path, class: 'text-danger' %> |
      <% end %>
        <%= link_to t('.log_out'), destroy_user_session_path, method: :delete %>
    <% else %>
        <%= link_to t('.sign_up'), new_user_registration_path %> |
        <%= link_to t('.log_in'), user_session_path %>
    <% end %> |
    <%= link_to t('.contacts'), email_messages_index_path %>
  </span>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <div class="text-right">
      <%= render 'layouts/footer' %>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>

    <div class="text-right">
      <%= render 'layouts/footer' %>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

  </body>

</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors' do %>
  <div>
    <h5 class="text-danger"><%= t('.header', count: resource.errors.count) %></h5>
      <% resource.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert"><%= message %></div>
      <% end %>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>

  <div class="alert alert-<%= alert_class(key) %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= message %>
  </div>
<% end %>