config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  get 'email_messages/index'
  post 'email_messages/create'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  # GET /test_passages/1/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :text, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  TEST_PASSED_PERCENT_VALUE = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def passed?
    result_percent >= TEST_PASSED_PERCENT_VALUE
  end

  def expired?
    # TestPassage created + Test.timer value < current time
    (created_at + self.test.timer * 60) < Time.zone.now
  end

  def timer_seconds_left
    # returns absolute value in seconds
    (Time.zone.now - (created_at + self.test.timer * 60)).to_i.abs
  end

  def result_percent
    percent = self.correct_questions.to_f / self.test.questions.count.to_f * 100
    percent.to_i
  end

  def passage_percent
    # current question index + 1 removed due progress bar incorrect visualization
    self.test.questions.index(current_question) * 100 / self.test.questions.count
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
      correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result gist]
  before_action :set_seconds_left, only: %i[show]
  before_action :check_expiration, only: %i[show update]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage), notice: t('.completed')
    else
      render :show
    end
  end

  def gist
    question = @test_passage.current_question
    service = GistQuestionService.new(question)
    result = service.call

    flash_options = if service.success?
                      current_user.gists.create(question_id: question.id, link: result.html_url)
                      { notice: t('.success_with_html', href: result.html_url) }
                    else
                      { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def set_seconds_left
    @seconds_left = @test_passage.timer_seconds_left
  end

  def check_expiration
    if @test_passage.expired?
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage), notice: t('.completed')
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<% if @test_passage.passed? %>
  <h2 style="color: green">
    <%= t('.success_result', percentage: @test_passage.result_percent) %>
  </h2>
<% else %>
  <h2 style="color: red">
    <%= t('.fail_result', percentage: @test_passage.result_percent) %>
  </h2>
<% end %>

<%= link_to t('.back'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<div id="seconds_left" style="display:none;"><%= @seconds_left %></div>
<div><%= t('.timer_value') %> <span id="timer"></span></div>

<div class="progress-bar-container">
  <%= content_tag :div,
      '',
      class: 'progress-bar',
      data: { percent: @test_passage.passage_percent } %>
</div>

<b><%= @test_passage.current_question.text %></b><br />

<i>
  <%=
    t('.counter',
    current: @test_passage.test.questions.index(@test_passage.current_question) + 1,
    total: @test_passage.test.questions.count)
  %>
</i>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :text, include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

  <p><%= link_to 'Gist question', gist_test_passage_path(@test_passage), method: :post %></p>
  <p><%= form.submit t('.next_question') %></p>
<% end %>