config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  get 'email_messages/index'
  post 'email_messages/create'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  # GET /test_passages/1/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :text, presence: true

  validate :validate_max

  private

  def validate_max
    question_count = question.nil? ? 0 : question.answers.size
    if question_count >= 4
      errors.add(:Quantity, 'Question must have 4 answers max!')
    end
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

class Admin::AnswersController < Admin::BaseController
  before_action :set_answer, only: %i[show edit update destroy]
  before_action :find_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_question_path(@answer.question), notice: 'Answer was created.'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_question_path(@answer.question)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:text, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<li>
  <%= answer.text %><br>
  <%= link_to 'Show', admin_answer_path(answer) %> |
  <%= link_to 'Edit', edit_admin_answer_path(answer) %> |
  <%= link_to 'Delete',
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  </li>

app/views/admin/answers/_form.html.erb
<%= form_with model: [:admin, @question, @answer], local: true do |form| %>
  <% render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, id: :answer_text, rows: 7, cols: 60 %>
  </p>

  <p>
    <%= form.label :correct %><br>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Editing Answer</h1>

<p><%= @answer.question.text %></p>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@answer.question) %>

app/views/admin/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_admin_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<p><%= @question.text %></p>

<%= render 'shared/errors', resource: @answer %>

<%= render 'form' %>
<%= link_to 'Back', admin_question_path(@question) %>

app/views/admin/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.text %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.text %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to 'Back', admin_question_path(@answer.question) %>