config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  get 'email_messages/index'
  post 'email_messages/create'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end
    member do
      post :start
    end
  end

  # GET /test_passages/1/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists

  validates :text, presence: true
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

class Admin::QuestionsController < Admin::BaseController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  before_action :define_test, only: %i[index new create]
  before_action :define_question, only: %i[show edit update destroy]

  def new
    @question = @test.questions.new
  end

  def show
    @answers = @question.answers
  end

  def edit; end

  def create
    question = @test.questions.new(question_params)

    if question.save
      redirect_to admin_test_path(question.test_id)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test_id)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test_id)
  end

  private

  def define_test
    @test = Test.find(params[:test_id])
  end

  def define_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:text)
  end

  def rescue_with_question_not_found
    render plain: "Question id:#{params[:id]} not exist!", status: 404
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header(question)
    "#{question.new_record? ? 'Create new' : 'Edit'} "\
      "'#{question.test.title}' test Question"
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <table>
      <tr>
        <%= render 'shared/errors', resource: @question %>

        <td>
            <%= form.label :text %>
            <%= form.text_field :text %>
        </td>
        <td>
             <%= form.submit %>
        </td>
      </tr>
  </table>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.text %></td>
  <td><%= link_to t('.info'), admin_question_path(question.id) %></td>
  <td><%= link_to t('.edit'), edit_admin_question_path(question.id) %></td>
  <td>
    <%= link_to t('.remove'),
      admin_question_path(question),
      method: :delete,
      data: { confirm: t('.confirm') }
    %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<%= question_header(@question) %>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test.id) %>

app/views/admin/questions/new.html.erb
<%= question_header(@question) %>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test.id) %>

app/views/admin/questions/show.html.erb
<h1>Question detalization</h1>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<h2>Answers</h2>

<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Edit', edit_admin_question_path(@question) %> |
<%= link_to 'Back', admin_test_path(@question.test) %>